### ISSUE TITLE
US 05.02.01 Process following request [Updated]

### ISSUE THREAD

**Issue by KevinTang2318** [CMPUT301F21T08/HabitTracker#26]
As a doer, I want to grant or deny another doer permission to follow all my public habits.
# Requirement breakdown
- In the new following request page, the user can click on each entry to ether accept or deny this request.
- If the user accept this request, the other user can start following the current user and can see current user's public habits
- If the user denies this request, access is not granted.

**Comment by Terry-One** [comment]
Accept, deny of the request done.
Showing the following list with basic information: Username done
